[Icon Theme]
Name=Oxygen
Inherits=default

DisplayDepth=32

DesktopDefault=32
DesktopSizes=16,22,32
ToolbarDefault=22
ToolbarSizes=16,22,32
MainToolbarDefault=22
MainToolbarSizes=16,22,32
SmallDefault=16
SmallSizes=16,22,32
PanelDefault=32
PanelSizes=16,22,32
DialogDefault=32
DialogSizes=16,22,32

Directories=16x16,22x22,32x32

[16x16]
Size=16
Type=Threshold

[22x22]
Size=22
Type=Threshold

[32x32]
Size=32
Type=Threshold
